#!/bin/bash
#! Name of the job:
#SBATCH -J DATAMOVE
#! Which project should be charged:
#SBATCH -A MRC-TOX-SL3-CPU
#! How many whole nodes should be allocated?
#SBATCH --nodes=1
#! How many (MPI) tasks will there be in total? (<= nodes*32)
#! The skylake/skylake-himem nodes have 32 CPUs (cores) each.
#SBATCH --ntasks=10
#! How much wallclock time will be required?
#SBATCH --time=12:00:00
#! What types of email messages do you wish to receive?
#SBATCH --mail-type=FAIL
#! Uncomment this to prevent the job from being requeued (e.g. if
#! interrupted by node failure or system downtime):
##SBATCH --no-requeue
#SBATCH -o logs/%j.log
#SBATCH -e logs/%j.err.log

#! For 6GB per CPU, set "-p skylake"; for 12GB per CPU, set "-p skylake-himem": 
#SBATCH -p icelake


. /etc/profile.d/modules.sh                # Leave this line (enables the module command)
module purge                               # Removes all modules still loaded
module load rhel7/default-peta4            # REQUIRED - loads the basic environment



cp ../../mm_fiber_wes/raw_data/F001/X204SC21030724-Z01-F001_*/raw_data/*/*.fq.gz data/.
cp ../../mm_fiber_wes/raw_data/WES-DATA_3_Batch/GB041021-JZC-3*/*/*/*fastq.gz data/.

