#!/bin/bash
#! Name of the job:
#SBATCH -J NRMAP_RE
#! Which project should be charged:
#SBATCH -A MRC-TOX-SL2-CPU
#! How many whole nodes should be allocated?
#SBATCH --nodes=1
#! How many (MPI) tasks will there be in total? (<= nodes*32)
#! The skylake/skylake-himem nodes have 32 CPUs (cores) each.
#SBATCH --ntasks=50
#! How much wallclock time will be required?
#SBATCH --time=16:00:00
#! What types of email messages do you wish to receive?
#SBATCH --mail-type=FAIL
#! Uncomment this to prevent the job from being requeued (e.g. if
#! interrupted by node failure or system downtime):
##SBATCH --no-requeue
#SBATCH -o logs/%j.log
#SBATCH -e logs/%j.err.log

#! For 6GB per CPU, set "-p skylake"; for 12GB per CPU, set "-p skylake-himem": 
#SBATCH -p icelake


. /etc/profile.d/modules.sh                # Leave this line (enables the module command)
module purge                               # Removes all modules still loaded
module load rhel7/default-peta4            # REQUIRED - loads the basic environment

/rds/project/rds-XUr6B1Jhndg/sb2534_Sina/tools/diamond blastx -p 50  -d /rds/project/rds-XUr6B1Jhndg/sb2534_Sina/databases/nr/nr.dmnd  -f 100 -o 07_ALIGN/$1 -q 06_WEIGHT/$1.fasta
