#!/bin/bash
#! Name of the job:
#SBATCH -J HISAT2
#! Which project should be charged:
#SBATCH -A MRC-TOX-SL3-CPU
#! How many whole nodes should be allocated?
#SBATCH --nodes=1
#! How many (MPI) tasks will there be in total? (<= nodes*32)
#! The skylake/skylake-himem nodes have 32 CPUs (cores) each.
#SBATCH --ntasks=20
#! How much wallclock time will be required?
#SBATCH --time=02:00:00
#! What types of email messages do you wish to receive?
#SBATCH --mail-type=FAIL
#! Uncomment this to prevent the job from being requeued (e.g. if
#! interrupted by node failure or system downtime):
##SBATCH --no-requeue
#SBATCH -o logs/%j.log
#SBATCH -e logs/%j.err.log

#! For 6GB per CPU, set "-p skylake"; for 12GB per CPU, set "-p skylake-himem": 
#SBATCH -p icelake


. /etc/profile.d/modules.sh                # Leave this line (enables the module command)
module purge                               # Removes all modules still loaded
module load rhel7/default-peta4            # REQUIRED - loads the basic environment

module load hisat2

hisat2 -p 20 -x /rds/project/rds-XUr6B1Jhndg/sb2534_Sina/databases/mouse/current/genome/mm39_Hisat2 -1 02_TRIMMED/$1.trimmed_1.fastq.gz -2 02_TRIMMED/$1.trimmed_2.fastq.gz -S 04_ALIGNED/$1.sam
samtools view -u 04_ALIGNED/$1.sam | samtools sort -o 05_SORTED/$1.sorted.bam
