#!/bin/bash
#! Name of the job:
#SBATCH -J FEATURECOUNTS
#! Which project should be charged:
#SBATCH -A MRC-TOX-SL3-CPU
#! How many whole nodes should be allocated?
#SBATCH --nodes=1
#! How many (MPI) tasks will there be in total? (<= nodes*32)
#! The skylake/skylake-himem nodes have 32 CPUs (cores) each.
#SBATCH --ntasks=20
#! How much wallclock time will be required?
#SBATCH --time=06:00:00
#! What types of email messages do you wish to receive?
#SBATCH --mail-type=FAIL
#! Uncomment this to prevent the job from being requeued (e.g. if
#! interrupted by node failure or system downtime):
##SBATCH --no-requeue
#SBATCH -o logs/%j.log
#SBATCH -e logs/%j.err.log

#! For 6GB per CPU, set "-p skylake"; for 12GB per CPU, set "-p skylake-himem": 
#SBATCH -p icelake


. /etc/profile.d/modules.sh                # Leave this line (enables the module command)
module purge                               # Removes all modules still loaded
module load rhel7/default-peta4            # REQUIRED - loads the basic environment

/rds/project/rds-XUr6B1Jhndg/sb2534_Sina/tools/subread-2.0.3-Linux-x86_64/bin/featureCounts -T 20 -p --countReadPairs -C -a /rds/project/rds-XUr6B1Jhndg/sb2534_Sina/databases/mouse/current/genome/mm39.ncbiRefSeq.gtf -o FeatureCounts.txt $1
