#!/bin/bash
#! Name of the job:
#SBATCH -J FILT_B5
#! Which project should be charged:
#SBATCH -A MRC-TOX-SL2-CPU
#! How many whole nodes should be allocated?
#SBATCH --nodes=1
#! How many (MPI) tasks will there be in total? (<= nodes*32)
#! The skylake/skylake-himem nodes have 32 CPUs (cores) each.
#SBATCH --ntasks=50
#! How much wallclock time will be required?
#SBATCH --time=24:00:00
#! What types of email messages do you wish to receive?
#SBATCH --mail-type=FAIL
#! Uncomment this to prevent the job from being requeued (e.g. if
#! interrupted by node failure or system downtime):
##SBATCH --no-requeue
#SBATCH -o logs/%j.log
#SBATCH -e logs/%j.err.log

#! For 6GB per CPU, set "-p skylake"; for 12GB per CPU, set "-p skylake-himem": 
#SBATCH -p icelake-himem


. /etc/profile.d/modules.sh                # Leave this line (enables the module command)
module purge                               # Removes all modules still loaded
module load rhel7/default-peta4            # REQUIRED - loads the basic environment

bowtie2 -p 50 --un-conc-gz 04_FILTER/$1.%.filtered.fastq.gz --un-gz 04_FILTER/$1.unpaired.filtered.fastq.gz -x <Bowtie2 host database> -1 02_TRIMMED/$1.trimmed_1.fastq.gz -2 02_TRIMMED/$1.trimmed_2.fastq.gz -S TEMP/$1.sam
samtools view -u TEMP/$1.sam | samtools sort -o 11_HOST/$1.sorted.bam

